language: node_js
node_js:
- node
before_install:
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
before_script:
- npm install
script:
- npm run build
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: "dev.mastho@gmail.com"
  api_key:
    secure: 110xVmSHk0NXHne8ZG1UvlfGA9zvDp37zRFndx8jaziqjBSsRfytbY/zdYlhX0S+hH8va9REKVBtX2pSVkvniWxGunEh03uwEr4nUDwULXHV9qFaKWVxK5qIIHGpMDh5T/B/55b7FvkmEaaxh9HQj1Jp0s1rztFM6kBuhttHQjeS52zEPXTNg+up4T+byaov+0Rg54F7X4njmLrDT+qI/MYZmZTJaFMxCy8t8Ogwf9jfTxqVfve/D4Sr12JhUYVIPyE/OXrkuGB5GFm0GYysdR58o4xRcQp4Oppsp5ZugG+qTZBqY8aPwjtfTkUlkbJYFEB9wCTF8UyMn/M5fkNvnnLVqPwVh4c6JC74r8FSYwrEhmVh24CEwuEBzZVQKJ9kOXnVPTY2yrtkfCKeNl4GDUDmCRiHTmH1mvJLIVIB2ZpJ5hYNNj4cIdtBTOrAgNTmxOAy0aOfPo3bED/b/Us5Dyyj0DMiViiqwUz7tMFhOsmDjaGlgP8vqIbXmrwbF1eoNeEGwHHlYBW8JuJ67UwxcC5OQKjmS4bbbCF0h6IahVZYQghgXBgS/tNar5WZlPSH112IqYc/9KMwwa/7a0JQCZMwPm5YvWbodCgcvgSbjs67nfB7NYVCjVDkN/Zaab3+r41niI5ZjYQlSVMzGAjttTO94USJMNALaz2d/GDVVP0=
  on:
    branch: master